using HealthcareAppointmentOps.Domain.Common;

namespace HealthcareAppointmentOps.Infrastructure.Pdf;

internal enum LabFlag { High, Low, Borderline, Normal }

internal sealed record Analyte(
    string Test,
    string Result,
    string Unit,
    string ReferenceRange,
    string Icd,
    string? Method,
    LabFlag Flag);

internal sealed record AnalyteSection(string Title, Analyte[] Rows);

internal sealed record Signatory(string Name, string Credentials, string Role, string Action, string Verification);

internal static class LabReportContent
{
    public const string LabDivision = "Diagnostics & Clinical Laboratory";
    public const string LabEmail = "labresults@meridianhealth.example";
    public const string LabWeb = "meridianhealth.example";

    public const string PanelTitle = "Laboratory Report";
    public const string PanelSubtitle = "Metabolic Panel  •  Lipid Panel  •  HbA1c";

    public const string FastingStatus = "Fasting (12 hrs)";
    public const string CollectedBy = "R. Okoye, CPT (venipuncture)";
    public const string OrderingGroupFallback = "Internal Medicine";

    public const string ActiveConditions =
        "Type 2 Diabetes Mellitus (E11.9);  Essential Hypertension (I10);  Hyperlipidemia (E78.5)";

    public static readonly AnalyteSection[] Sections =
    [
        new("Glycemic Markers",
        [
            new("Hemoglobin A1c", "6.8", "%", "< 5.7", "E11.9",
                "HPLC, NGSP-certified. Care-plan goal A1c < 6.5%.", LabFlag.High),
            new("Fasting Glucose", "128", "mg/dL", "70 – 99", "R73.09",
                "Enzymatic hexokinase.", LabFlag.High)
        ]),
        new("Lipid Panel",
        [
            new("LDL Cholesterol", "118", "mg/dL", "< 100", "E78.5",
                "Calculated (Friedewald). Goal LDL < 100 mg/dL; atorvastatin 20 mg initiated.", LabFlag.Borderline),
            new("HDL Cholesterol", "52", "mg/dL", "≥ 40", "E78.5",
                "Direct enzymatic.", LabFlag.Normal)
        ]),
        new("Thyroid",
        [
            new("Thyroid Stimulating Hormone (TSH)", "2.1", "mIU/L", "0.4 – 4.0", "E07.9",
                "Electrochemiluminescence immunoassay.", LabFlag.Normal)
        ]),
        new("Renal",
        [
            new("Creatinine", "0.9", "mg/dL", "0.6 – 1.3", "I10",
                "Enzymatic, IDMS-traceable.", LabFlag.Normal)
        ])
    ];

    public const string Interpretation =
        "Metabolic panel shows hemoglobin A1c slightly above target at 6.8% (goal < 6.5%), with fasting " +
        "glucose elevated at 128 mg/dL — findings consistent with sub-optimally controlled type 2 diabetes " +
        "mellitus. LDL cholesterol is high-normal at 118 mg/dL (goal < 100 mg/dL); atorvastatin 20 mg has " +
        "been initiated per the current care plan. HDL, TSH, and renal function are within reference range " +
        "and no critical values were observed. Recommend continued lifestyle reinforcement, home glucose " +
        "monitoring, and a repeat metabolic and lipid panel in 8 weeks.";

    public const string AdditionalInformation =
        "All testing was performed in compliance with CLIA and CAP accreditation standards. Reference ranges " +
        "are method- and instrument-specific and may differ between laboratories. Instruments undergo routine " +
        "maintenance, calibration, and daily quality-control verification. This report was generated by the " +
        "Meridian Health Laboratory Information System from seeded demonstration data.";

    public const string ConfidentialTitle = "CONFIDENTIAL — PROTECTED HEALTH INFORMATION";
    public const string ConfidentialBody =
        "This laboratory report contains confidential patient information protected under HIPAA. Unauthorized " +
        "review, use, or disclosure is prohibited. Results should be interpreted by a qualified healthcare " +
        "professional within the context of the patient's overall clinical presentation.";

    public static readonly Signatory Reviewer =
        new("Dr. Priya Nair", "MD, PhD, Clinical Chemistry", "Clinical Chemistry Specialist", "Reviewed", "[digitally signed]");

    public static readonly Signatory Authorizer =
        new("Dr. Marcus Feld", "MD, FCAP", "Laboratory Medical Director", "Authorized", "[electronically verified]");

    public static string LabIdentity => $"{Brand.OrganizationName} — {LabDivision}";

    public static string FlagText(LabFlag flag) => flag switch
    {
        LabFlag.High => "HIGH",
        LabFlag.Low => "LOW",
        LabFlag.Borderline => "BORDERLINE",
        _ => "NORMAL"
    };
}
